### ISSUE TITLE
Rename the current Mirror Test Harness to "Latency", create a new "Load/Stress" test harness

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/TestingAndReporting#19]
After thinking about the mechanisms required to faithfully measure the traffic latency versus the mechanisms required to create a configurable load/stress test harness, I think the best idea would be to tie off the development of the current harness and start development on a new one. The latency measurements require that we keep track of linked client/target connections, whereas, with a load testing environment (with user defined traffic, etc.) this would be too difficult to manage given the existing design of the current "mirror" harness.

We would basically rename the current harness from "mirror" to "latency" and create a new test harness called "stress". The "load/stress" harness would focus more on multiple configurations, connection and traffic shaping, etc. In its current incarnation, the "latency" harness would require too much rework.

Note that issues #15, #16, #17 and #18 deal with functionality in the Load/Stress harness, and not the existing Latency harness.

## Objectives
* [x] In the repo, rename `src/mirror` to `src/latency`
* [x] Create a new Load/Stress test harness in the the `src/stress` directory
* [x] Label the issues appropriately

**Comment by creindle** [comment]
Just to be clear, does this PR: https://github.com/vistadataproject/TestingAndReporting/pull/21 address "Create a new Load/Stress test harness"?
