### ISSUE TITLE
Perform Some Housekeeping

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/TestingAndReporting#4]
## Objectives
* [x] Move 'genericHarness' into 'src/mirror/index.js'
* [x] Lock down the terminology in the code
    * "client" = Harness connection initiators
    * "target" = Harness "client" target (server)
    * "server" = Harness server socket
* [x] Split the `port` member of the `Harness` class into two values:
   * "target" TCP Port (i.e. the TCP port that the `Harness` clients try to connect to)
   * "server" TCP Port (i.e. the TPC port that the `Harness` uses to open up the server socket connection)

**Comment by creindle** [comment]
Hey Mike, I just completed these tasks. I believe I did got the terminology correct? Please let me know if I'm wrong.

**Comment by mfuroyama** [comment]
Looks good!
