### ISSUE TITLE
Support Timed Client Send

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/TestingAndReporting#5]
We want to be able to maintain concurrent connections over periods of time to test and observe the effects of sustained network traffic to the RPC Mirror from concurrent sources. The length of time that the concurrent connections stay open should be a configurable value.

## Objectives
* [x] Modify the client data send routines to send not just one message, but continuous messages over a specified duration of time.
* [x] Add the time duration to the set of configurable **Harness** runtime options
* [x] Monitor and collect statistics for each client transmission during the runtime period
* [x] Alter the reported statistics to include updated measurements

**Comment by creindle** [comment]
I just pushed up changes to support this!! Woo!! I'm thinking of adding a progress bar once I finish the necessities.

**Comment by creindle** [comment]
Ah I should've made a PR...

**Comment by mfuroyama** [comment]
Pull request would have been nice...
