### ISSUE TITLE
Fix issues associated with Issue #5

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/TestingAndReporting#9]
This issue is in lieu of what would have been a code review against a pull request for issue #5:

* [x] [src/mirror/index.js#L13](https://github.com/vistadataproject/TestingAndReporting/blob/d6ecdae242d7cb439f2e94da5a81e582232b8054/src/mirror/index.js#L13): Let's turn the parameter initialization list into an options object. You can enforce values using object destructuring and defaults
* [x] [examples/testGenericHarness.js#L12](https://github.com/vistadataproject/TestingAndReporting/blob/d6ecdae242d7cb439f2e94da5a81e582232b8054/examples/testGenericHarness.js#L12): A `usage` and `--help/-h` option describing the params and meanings here would a "nice to have" since there are so many options. This would also help you as the developer remember the options as quasi-documentation
* [x] `node testGenericHarness.js -s 9090 -f 10000` crashes the test. Are you handling the command line options properly? (i.e. converting the strings parameters into numbers)

Fix these, especially the last item, preferably in a pull request, and we can continue discussion.

**Comment by mfuroyama** [comment]
@creindle Please prioritize this one

**Comment by creindle** [comment]
I just pushed up the changes to address these:

**Comment by mfuroyama** [comment]
Found more issues. Will close this issue and open a new issue containing the issues associated with this issue.
